# Generated by Django 4.2.26 on 2025-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nba_id',
            field=models.IntegerField(blank=True, help_text='Official NBA ID', null=True),
        ),
    ]
